version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: go build
      
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: test-results
  test-coverage:
      working_directory: ~/repo
      docker:
        - image: circleci/golang:1.16
      steps:
        
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: go build
      - run: 
            name: "go cov dependecies"
            command: go get github.com/axw/gocov/gocov
      - run: 
            name: "go xml dependecies"
            command: go get github.com/AlekSi/gocov-xml
      - run:
          command: |
                go test -coverprofile=cover.out
                go tool cover -html=cover.out -o coverage.html
                mv coverage.html /tmp/artifacts
      - run:
          command: |
                mkdir test-results
                cd test-results
                mkdir go
      - run:
            name: "conver to xml for circleCI"
            command: gocov convert cover.out | gocov-xml > test-results/go/coverage.xml
      - store_test_results:
                path: test-results
      